### ISSUE TITLE
tips. WordPress

### ISSUE THREAD

**Issue by wdssmq** [wdssmq/zbp-docker-compose#3]
```yml
    wp_def:
        image: wordpress:latest
        restart: unless-stopped
        ports:
            - "8082:80"
        environment:
            WORDPRESS_DB_HOST: MySQL
            WORDPRESS_DB_NAME: docker_wp_def
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD:-shujukumima1233}
        volumes:
            - ./data-www/wp_def:/var/www/html
        depends_on:
            - MySQL
        networks:
            - net_web

```

和 Z-BlogPHP 不同，需要先在数据库中创建好数据库：

```bash
sudo docker exec -it MySQL mysql \
    -uroot -pDBPWD \
    -e "CREATE DATABASE docker_wp_def DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
```
