### ISSUE TITLE
note. sapic 部署「图床」

### ISSUE THREAD

**Issue by wdssmq** [wdssmq/zbp-docker-compose#4]
```yml
version: '3'
services:
  sapic:
    image: staugur/sapic
    restart: always
    ports:
      - "9514:9514"
    environment:
      - sapic_redis_url=redis://@redis:6379
      # 设置信任代理标头
      #- sapic_proxyfix=true
    volumes:
      - static:/picbed/static/
      - ./data/picbed-upload/:/picbed/static/upload/
    depends_on:
      - "redis"

  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis-data/:/data/

volumes:
  static:

# docker-compose exec sapic flask sa create -u 管理员账号 -p 密码 --isAdmin
```
