### ISSUE TITLE
note. Gitea

### ISSUE THREAD

**Issue by wdssmq** [wdssmq/zbp-docker-compose#5]
```yaml
    # gitea
    gitea:
        image: gitea/gitea:1.18.3
        container_name: gitea
        restart: always
        env_file:
            - ./conf/common.env
        environment:
            - USER_UID=1000
            - USER_GID=1000
            - GITEA__database__DB_TYPE=mysql
            - GITEA__database__HOST=MySQL:3306
            - GITEA__database__NAME=docker_gitea
            - GITEA__database__USER=root
            #   - GITEA__database__PASSWD=PASSWD
        volumes:
            - ./gitea-data:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "3000:3000"
            - "222:22"
        depends_on:
            - MySQL
        networks:
            - net_web
```
`GITEA__database__PASSWD` 可以在 `conf/common.env` 中指定；
